name: Publish Docker image
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: aikocute/aikoxrayr
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7,linux/s390x,aix/ppc64,android/386,android/amd64,android/arm,android/arm64,darwin/amd64,darwin/arm64,dragonfly/amd64,freebsd/386,freebsd/amd64,freebsd/arm,freebsd/arm64,illumos/amd64,ios/amd64,ios/arm64,js/wasm,linux/386,linux/amd64,linux/arm,linux/arm64,linux/mips,linux/mips64,linux/mips64,linux/mipsle,linux/ppc64,linux/ppc64le,linux/riscv64,netbsd/386,netbsd/amd64,netbsd/arm,netbsd/arm64,plan9/386,plan9/amd64,plan9/arm,solaris/amd64,windows/386,windows/arm,windows/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}